## 실습

In [1]:
import pandas as pd
df = pd.read_csv('ns_202104.csv')
df = df.drop(columns='Unnamed: 13', axis =1)
df.head()

C:\Users\karac\AppData\Local\Temp\ipykernel_19700\4220453423.py:2: DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('ns_202104.csv')

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [4]:
### 가장많이 언급된 출판사 1위를 선정해 각 df를 만드시오
### 출판사가 언급된거(value_counts)
count = df['출판사'].value_counts()
count

출판사
문학동네                   5041
민음사                    4204
김영사                    3577
웅진씽크빅                  3394
시공사                    2871
                       ...
큰솔                        1
전북대학교  20세기민중생활사연구소       1
모루와정                      1
드림엔터                      1
건강다이제스트                   1
Name: count, Length: 21914, dtype: int64

In [5]:
munhak = df[df['출판사'] == '문학동네']
munhak.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
23,24,어쩌면 스무 번,편혜영 지음,문학동네,2021,9788954677608,NaN,NaN,NaN,NaN,1,0,2021-03-19
48,49,실크 스타킹 한 켤레,"세라 오언 주잇 외 지음, 정소영 옮김",문학동네,2021,9788954677523,NaN,NaN,NaN,843,1,1,2021-03-16
51,52,나는 내가 싫고 좋고 이상하고,백은선 지음,문학동네,2021,9788954677233,NaN,NaN,NaN,814.7,1,1,2021-03-16
54,55,호박색 밤,"실비 제르맹 지음, 이창실 옮김",문학동네,2021,9788954675543,NaN,NaN,NaN,863,1,0,2021-03-16
85,86,버터도 달걀도 필요 없는 건강빵 - 3분 손반죽으로 완성하는 비밀 레시피,"유키에 (지은이), 김유미 (옮긴이)",문학동네,2020,9788954675796,NaN,NaN,NaN,594.71,1,1,2021-03-15

In [24]:
### 연도별 대출건수를 구한 후 대출건수를 기준으로 내림차순 정리하시오
pd.DataFrame(df.groupby(['발행년도'])['대출건수'].sum()).reset_index().sort_values(by='대출건수', ascending=False)

            발행년도    대출건수
169         2008  329972
160         2005  324526
177         2009  314999
167         2007  294836
184         2010  292966
..           ...     ...
47         1979.       0
49         1980.       0
51         1981.       0
53         1982.       0
399  사회문화연구소 출판부       0

[400 rows x 2 columns]

발행년도가 없는 출판사를 찾아, 출판사별 '발행년도 최빈값'으로 채워넣으시오
최종 df를 확인했을때 발행년도의 결측치가 0이여야함
단, 발행년도가 없을 시 랜덤년도 기입
단, 출판사가 없을 시 '출판사 없음' 입력

In [30]:
### 발행년도가 없는 값을 뽑아 df로 만드시오
import numpy as np
no_year = df[df['발행년도'].isnull()]
no_year.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
31615,31616,본격 한중일 세계사 5,굽시니스트 지음,위즈덤하우스,NaN,9791190065092,NaN,NaN,NaN,NaN,0,0,2019-05-28
40140,40141,정책금융의 현황과 발전과제,정책금융연구회,한국산업은행,NaN,9788992784108,NaN,NaN,NaN,327.1,1,0,2019-01-22
40267,40268,서울지역 유적 발굴조사 총서 3,서울역사박물관,서울역사박물관,NaN,9791186324714,9791186324431,NaN,NaN,NaN,0,0,2019-01-22
214582,214583,食品新素材學,生體機能調節 天然素材硏究會 編,한림원,NaN,9788985670180,NaN,9,NaN,574,1,1,2010-04-12
264714,264715,Educative democracy:John stuart mill on educat...,by F. W. Garforth,NaN,NaN,9780197134382,NaN,NaN,NaN,370.73,1,0,2008-02-13

In [35]:
#단, 출판사가 없을 시 '출판사 없음' 입력 후 df 확인
no_year = df[df['발행년도'].isnull()]
no_year['출판사'].fillna('출판사 없음', inplace=True)
no_year.head()

C:\Users\karac\AppData\Local\Temp\ipykernel_19700\2180267640.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  no_year['출판사'].fillna('출판사 없음', inplace=True)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
31615,31616,본격 한중일 세계사 5,굽시니스트 지음,위즈덤하우스,NaN,9791190065092,NaN,NaN,NaN,NaN,0,0,2019-05-28
40140,40141,정책금융의 현황과 발전과제,정책금융연구회,한국산업은행,NaN,9788992784108,NaN,NaN,NaN,327.1,1,0,2019-01-22
40267,40268,서울지역 유적 발굴조사 총서 3,서울역사박물관,서울역사박물관,NaN,9791186324714,9791186324431,NaN,NaN,NaN,0,0,2019-01-22
214582,214583,食品新素材學,生體機能調節 天然素材硏究會 編,한림원,NaN,9788985670180,NaN,9,NaN,574,1,1,2010-04-12
264714,264715,Educative democracy:John stuart mill on educat...,by F. W. Garforth,출판사 없음,NaN,9780197134382,NaN,NaN,NaN,370.73,1,0,2008-02-13

In [46]:
#발행년도가 없는 출판사를 찾아, 출판사별 '발행년도 최빈값'으로 채워넣으시오
#힌트! 발행년도가 없는 출판사의 리스트를 뽑아 for loop처리!
no_year = df[df['발행년도'].isnull()]['출판사'].unique()
for publisher in no_year:
    years = df[(df['출판사'] == publisher) & (~df['발행년도'].isnull())]['발행년도']
    if not years.empty:
        mode_year = years.mode().values[0]
        df.loc[(df['출판사'] == publisher) & (df['발행년도'].isnull()), '발행년도'] = mode_year
df

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
401677,401678,韓國現代詩大系,채만묵 編著,한국문화사,1996,9788977352971,9788977352988.0,NaN,3,811.608,1,0,1970-01-01
401678,401679,뉴 웨이브,제임스 모나코 지음,한나래,1996,9788985367448,9788985367424.0,NaN,2,688.04,1,0,1970-01-01
401679,401680,(최인훈 장편소설)화두,최인훈 지음,민음사,1994,9788937401596,9788937401589.0,NaN,2,813.6,1,0,1970-01-01
401680,401681,독일 문학과 세계 문학,吳漢鎭 編著,벽호,1995,9788947700368,9788947700405.0,NaN,3,809.05,2,0,1970-01-01
401681,401682,참으로 소중한 생각,김일상 지음,동문사,1995,9788970610092,9788970610092.0,0,1,814.6,0,0,1970-01-01

In [53]:
#df발행년도 결측치 확인
no_year = df['발행년도'].isnull()
no_year_df = df[missing_years]
no_year_df

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
40140,40141,정책금융의 현황과 발전과제,정책금융연구회,한국산업은행,NaN,9788992784108,NaN,NaN,NaN,327.1,1,0,2019-01-22